"""empty message

Revision ID: b01ef8e186b7
Revises: dd6d5bc9fa00
Create Date: 2020-09-06 19:51:01.477190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01ef8e186b7'
down_revision = 'dd6d5bc9fa00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'balance', ['id'])
    op.create_unique_constraint(None, 'transaction', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'transaction', type_='unique')
    op.drop_constraint(None, 'balance', type_='unique')
    # ### end Alembic commands ###
